### ISSUE TITLE
Problems when using DeepPhospho App

### ISSUE THREAD

**Issue by yuz2011** [weizhenFrank/DeepPhospho#7]
Hi,
I use Launch_DeepPhospho_Desktop.cmd to test my dataset. The input contains more "charge/peptide" than output. It seems that some "charge/peptide" can not be predicted depending on the model used. Do you know why? Thank you very much!

config.png contains the parameters used. miss.txt contains some missing phosphopeptides after processing by DeepPhospho.

Best,
Yu
<img width="813" alt="config" src="https://user-images.githubusercontent.com/106479481/208887754-564af606-c7e6-4090-a621-f062214a0b79.png">
<img width="819" alt="config2" src="https://user-images.githubusercontent.com/106479481/208888164-fb723240-ab8f-4c89-b8cb-8fe87b547eb7.png">
[miss.txt](https://github.com/weizhenFrank/DeepPhospho/files/10276994/miss.txt)

**Comment by gureann** [comment]
Hi Yu,

This might sometimes happen when the predicted spectra of peptides have <4 fragments with >5% relative intensity. 
We have a simple rule to make sure the predicted spectra have relatively higher quality: all fragments should have relative intensity >5%; and each peptide should have at least 4 fragments after the previous filtering.
Currently we don't have explicit parameters to control this behavior. If you want all results to be reported, please consider modify these numbers: 
- in file `./deep_phospho/proteomics_utils/gen_dp_lib.py` `line 71`, change this `<= 5` to `<= 1` or `<= 0` will make the exclusion of fragments with only relative intensity < 1% or no exclusion
- same file and `line 83`, change this `>= 4` to `>= 3` will make the minimum number of fragments per precursor from 4 to 3

Best,
Ronghui

**Comment by yuz2011** [comment]
Thank you very much for you reply. That helps a lot.

Best,
Yu
